const sticker_vn_choki = {
  site_code: 'vn',
  imgArr: [
    { id: '0001', url: require(`@/assets/sticker/shrimp_vn_new/1d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0002', url: require(`@/assets/sticker/shrimp_vn_new/2d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0003', url: require(`@/assets/sticker/shrimp_vn_new/3d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0004', url: require(`@/assets/sticker/shrimp_vn_new/4d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0005', url: require(`@/assets/sticker/shrimp_vn_new/5d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0006', url: require(`@/assets/sticker/shrimp_vn_new/6d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0007', url: require(`@/assets/sticker/shrimp_vn_new/7d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0008', url: require(`@/assets/sticker/shrimp_vn_new/8d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0009', url: require(`@/assets/sticker/shrimp_vn_new/9d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0010', url: require(`@/assets/sticker/shrimp_vn_new/10d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0011', url: require(`@/assets/sticker/shrimp_vn_new/11d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0012', url: require(`@/assets/sticker/shrimp_vn_new/12d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0013', url: require(`@/assets/sticker/shrimp_vn_new/13d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0014', url: require(`@/assets/sticker/shrimp_vn_new/14d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0015', url: require(`@/assets/sticker/shrimp_vn_new/15d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0016', url: require(`@/assets/sticker/shrimp_vn_new/16d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0017', url: require(`@/assets/sticker/shrimp_vn_new/17d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0018', url: require(`@/assets/sticker/shrimp_vn_new/18d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0019', url: require(`@/assets/sticker/shrimp_vn_new/19d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0020', url: require(`@/assets/sticker/shrimp_vn_new/20d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0021', url: require(`@/assets/sticker/shrimp_vn_new/21d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0022', url: require(`@/assets/sticker/shrimp_vn_new/22d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0023', url: require(`@/assets/sticker/shrimp_vn_new/23d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0024', url: require(`@/assets/sticker/shrimp_vn_new/24d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0025', url: require(`@/assets/sticker/shrimp_vn_new/25d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0026', url: require(`@/assets/sticker/shrimp_vn_new/26d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0027', url: require(`@/assets/sticker/shrimp_vn_new/27d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0028', url: require(`@/assets/sticker/shrimp_vn_new/28d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0029', url: require(`@/assets/sticker/shrimp_vn_new/29d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0030', url: require(`@/assets/sticker/shrimp_vn_new/30d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0031', url: require(`@/assets/sticker/shrimp_vn_new/31d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0032', url: require(`@/assets/sticker/shrimp_vn_new/32d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0033', url: require(`@/assets/sticker/shrimp_vn_new/33d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0034', url: require(`@/assets/sticker/shrimp_vn_new/34d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0035', url: require(`@/assets/sticker/shrimp_vn_new/35d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0036', url: require(`@/assets/sticker/shrimp_vn_new/36d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0037', url: require(`@/assets/sticker/shrimp_vn_new/37d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0038', url: require(`@/assets/sticker/shrimp_vn_new/38d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0039', url: require(`@/assets/sticker/shrimp_vn_new/39d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0040', url: require(`@/assets/sticker/shrimp_vn_new/40d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0041', url: require(`@/assets/sticker/shrimp_vn_new/41d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0042', url: require(`@/assets/sticker/shrimp_vn_new/42d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0043', url: require(`@/assets/sticker/shrimp_vn_new/43d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0044', url: require(`@/assets/sticker/shrimp_vn_new/44d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0045', url: require(`@/assets/sticker/shrimp_vn_new/45d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0046', url: require(`@/assets/sticker/shrimp_vn_new/46d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0047', url: require(`@/assets/sticker/shrimp_vn_new/47d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0048', url: require(`@/assets/sticker/shrimp_vn_new/48d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0049', url: require(`@/assets/sticker/shrimp_vn_new/49d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0050', url: require(`@/assets/sticker/shrimp_vn_new/50d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0051', url: require(`@/assets/sticker/shrimp_vn_new/51d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0052', url: require(`@/assets/sticker/shrimp_vn_new/52d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0053', url: require(`@/assets/sticker/shrimp_vn_new/53d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0054', url: require(`@/assets/sticker/shrimp_vn_new/54d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0055', url: require(`@/assets/sticker/shrimp_vn_new/55d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0056', url: require(`@/assets/sticker/shrimp_vn_new/56d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0057', url: require(`@/assets/sticker/shrimp_vn_new/57d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0058', url: require(`@/assets/sticker/shrimp_vn_new/58d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0059', url: require(`@/assets/sticker/shrimp_vn_new/59d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0060', url: require(`@/assets/sticker/shrimp_vn_new/60d.png`), sticker_package_id: 'sticker_vn_choki' },
    { id: '0061', url: require(`@/assets/sticker/shrimp_vn_new/61d.png`), sticker_package_id: 'sticker_vn_choki' },
  ]
}
export {
  sticker_vn_choki
}
