const sticker_vn_ronaldo = {
  site_code: 'vn',
  imgArr: [
    { id: '0001', url: require(`@/assets/sticker/shrimp_vn_new/0001@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0002', url: require(`@/assets/sticker/shrimp_vn_new/0002@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0003', url: require(`@/assets/sticker/shrimp_vn_new/0003@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0004', url: require(`@/assets/sticker/shrimp_vn_new/0004@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0005', url: require(`@/assets/sticker/shrimp_vn_new/0005@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0006', url: require(`@/assets/sticker/shrimp_vn_new/0006@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0007', url: require(`@/assets/sticker/shrimp_vn_new/0007@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0008', url: require(`@/assets/sticker/shrimp_vn_new/0008@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0009', url: require(`@/assets/sticker/shrimp_vn_new/0009@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0010', url: require(`@/assets/sticker/shrimp_vn_new/0010@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0011', url: require(`@/assets/sticker/shrimp_vn_new/0011@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0012', url: require(`@/assets/sticker/shrimp_vn_new/0012@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0013', url: require(`@/assets/sticker/shrimp_vn_new/0013@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0014', url: require(`@/assets/sticker/shrimp_vn_new/0014@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0015', url: require(`@/assets/sticker/shrimp_vn_new/0015@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0016', url: require(`@/assets/sticker/shrimp_vn_new/0016@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0017', url: require(`@/assets/sticker/shrimp_vn_new/0017@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0018', url: require(`@/assets/sticker/shrimp_vn_new/0018@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0019', url: require(`@/assets/sticker/shrimp_vn_new/0019@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0020', url: require(`@/assets/sticker/shrimp_vn_new/0020@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0021', url: require(`@/assets/sticker/shrimp_vn_new/0021@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0022', url: require(`@/assets/sticker/shrimp_vn_new/0022@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0023', url: require(`@/assets/sticker/shrimp_vn_new/0023@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0024', url: require(`@/assets/sticker/shrimp_vn_new/0024@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0025', url: require(`@/assets/sticker/shrimp_vn_new/0025@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0026', url: require(`@/assets/sticker/shrimp_vn_new/0026@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0027', url: require(`@/assets/sticker/shrimp_vn_new/0027@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0028', url: require(`@/assets/sticker/shrimp_vn_new/0028@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0029', url: require(`@/assets/sticker/shrimp_vn_new/0029@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0030', url: require(`@/assets/sticker/shrimp_vn_new/0030@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0031', url: require(`@/assets/sticker/shrimp_vn_new/0031@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
    { id: '0032', url: require(`@/assets/sticker/shrimp_vn_new/0032@.png`), sticker_package_id: 'sticker_vn_ronaldo' },
  ]
}
export {
  sticker_vn_ronaldo
}
