const xiaxiaobian_vn = {
  site_code: 'vn',
  imgArr: [
    { id: '0001', url: require(`@/assets/sticker/shrimp_vn_new/1c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0002', url: require(`@/assets/sticker/shrimp_vn_new/2c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0003', url: require(`@/assets/sticker/shrimp_vn_new/3c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0004', url: require(`@/assets/sticker/shrimp_vn_new/4c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0005', url: require(`@/assets/sticker/shrimp_vn_new/5c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0006', url: require(`@/assets/sticker/shrimp_vn_new/6c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0007', url: require(`@/assets/sticker/shrimp_vn_new/7c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0008', url: require(`@/assets/sticker/shrimp_vn_new/8c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0009', url: require(`@/assets/sticker/shrimp_vn_new/9c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0010', url: require(`@/assets/sticker/shrimp_vn_new/10c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0011', url: require(`@/assets/sticker/shrimp_vn_new/11c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0012', url: require(`@/assets/sticker/shrimp_vn_new/12c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0013', url: require(`@/assets/sticker/shrimp_vn_new/13c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0014', url: require(`@/assets/sticker/shrimp_vn_new/14c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0015', url: require(`@/assets/sticker/shrimp_vn_new/15c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0016', url: require(`@/assets/sticker/shrimp_vn_new/16c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0017', url: require(`@/assets/sticker/shrimp_vn_new/17c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0018', url: require(`@/assets/sticker/shrimp_vn_new/18c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0019', url: require(`@/assets/sticker/shrimp_vn_new/19c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0020', url: require(`@/assets/sticker/shrimp_vn_new/20c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0021', url: require(`@/assets/sticker/shrimp_vn_new/21c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0022', url: require(`@/assets/sticker/shrimp_vn_new/22c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0023', url: require(`@/assets/sticker/shrimp_vn_new/23c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0024', url: require(`@/assets/sticker/shrimp_vn_new/24c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0025', url: require(`@/assets/sticker/shrimp_vn_new/25c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0026', url: require(`@/assets/sticker/shrimp_vn_new/26c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0027', url: require(`@/assets/sticker/shrimp_vn_new/27c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0028', url: require(`@/assets/sticker/shrimp_vn_new/28c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0029', url: require(`@/assets/sticker/shrimp_vn_new/29c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0030', url: require(`@/assets/sticker/shrimp_vn_new/30c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0031', url: require(`@/assets/sticker/shrimp_vn_new/31c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0032', url: require(`@/assets/sticker/shrimp_vn_new/32c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0033', url: require(`@/assets/sticker/shrimp_vn_new/33c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0034', url: require(`@/assets/sticker/shrimp_vn_new/34c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0035', url: require(`@/assets/sticker/shrimp_vn_new/35c.png`), sticker_package_id: 'xiaxiaobian_vn' },
    { id: '0036', url: require(`@/assets/sticker/shrimp_vn_new/36c.png`), sticker_package_id: 'xiaxiaobian_vn' },
  ]
}
export {
  xiaxiaobian_vn
}
